#!/bin/bash

set -e

VERSION="0.4.0"
BASE_URL="https://storage.slv.dev/slv"

detect_platform() {
  uname_out="$(uname -s)"
  case "${uname_out}" in
    Linux*)     platform="x86_64-unknown-linux-gnu"; osfamily="linux";;
    Darwin*)    platform="x86_64-apple-darwin"; osfamily="darwin";;
    CYGWIN*|MINGW*|MSYS*|Windows*) platform="x86_64-pc-windows-msvc"; osfamily="windows";;
    *)          echo "Unsupported platform: ${uname_out}" && exit 1;;
  esac
}

install_slv() {
  echo "Detecting platform..."
  detect_platform
  echo "Platform detected: $platform"

  DOWNLOAD_URL="${BASE_URL}/${VERSION}/${platform}-exe.tar.gz?cachebuster=$(date +%s)"
  TEMPLATE_URL="${BASE_URL}/template/${VERSION}/template.tar.gz?cachebuster=$(date +%s)"
  INSTALL_DIR="/usr/local/bin"
  TEMPLATE_DIR="$HOME/.slv/template"
  TEMP_DIR=$(mktemp -d)
  mkdir -p "$HOME/.slv"
  mkdir -p "$HOME/.slv/keys"

  echo "Temporary directory: $TEMP_DIR"

  echo "Downloading slv from $DOWNLOAD_URL..."
  curl -fsSL "$DOWNLOAD_URL" -o "$TEMP_DIR/slv.tar.gz"

  echo "Downloading templates from $TEMPLATE_URL..."
  curl -fsSL "$TEMPLATE_URL" -o "$HOME/.slv/template.tar.gz"
  
  echo "Extracting slv..."
  tar -xzvf "$TEMP_DIR/slv.tar.gz" -C "$TEMP_DIR" --strip-components=1

  echo "Extracting templates..."
  tar -xzvf "$HOME/.slv/template.tar.gz" -C "$HOME/.slv" --strip-components=1
  mkdir -p "$HOME/.slv/template"
  echo "Copying templates to $HOME/.slv/template"

  SLV_FILE="$TEMP_DIR/slv-x86_64-apple-darwin-exe"
  if [ "$platform" = "x86_64-unknown-linux-gnu" ]; then
    SLV_FILE="$TEMP_DIR/slv-x86_64-unknown-linux-gnu-exe"
  fi
  TEMPLATE_DL_DIR="$HOME/.slv/"

  if [ ! -f "$SLV_FILE" ]; then
    echo "Error: Extracted file not found."
    exit 1
  fi

  echo "Installing slv..."
  if [ ! -d "$INSTALL_DIR" ]; then
    echo "$INSTALL_DIR does not exist. Creating it..."
    sudo mkdir -p "$INSTALL_DIR"
  fi

  sudo mv "$SLV_FILE" "$INSTALL_DIR/slv"
  sudo chmod +x "$INSTALL_DIR/slv"

  echo "Cleaning up..."
  rm -rf "$TEMP_DIR"
  rm -rf "$TEMP_DIR2"
  rm -rf "$HOME/.slv/template.tar.gz"

  echo "slv has been installed successfully!"
  echo "Ensure $INSTALL_DIR is in your PATH."
  mkdir -p ~/.slv/keys
  slv -P
}

install_slv